<a href="https://colab.research.google.com/github/KNIGHTKRUBPOM/Programming_Fundamentals/blob/main/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015155 ชื่อ อธิชนัน จันทมิตร

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที

In [ ]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0:
        return True
    elif year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 0
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365

Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ

In [ ]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0 and year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 1
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    d1,m1,y1 = date1.split("-")
    d2,m2,y2 = date2.split("-")
    d1,m1,y1 = int(d1),int(m1),int(y1)
    d2,m2,y2 = int(d2),int(m2),int(y2)
    num1 = day_in_year(y1) - day_of_year(d1, m1, y1) + 2
    num2 = day_of_year(d2, m2, y2)
    if y2 - y1 > 1:
        count = 0
        count_for = y2 - y1
        for i in range(count_for):
            if i == 0:
                continue
            count += day_in_year(y1 + i)
        return(num1 + num2  + count)-1

    if y1 == y2:
        return num1
    else:
        return(num1 + num2)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 367 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

731
76
367
367
367
365

Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1

In [ ]:
def leap_year(year):
    if year % 100 != 0 and year % 4 == 0 and year % 400 == 0:
        return True
    else:
       return False

def day_of_year(day, month, year):
    sum_month = 1
    if leap_year(year) == True:
        days_in_month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

    if leap_year(year) == False:
        days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        for i in range(month - 1):
            sum_month += days_in_month[i]
        return(sum_month + day)

def day_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    try:
        d1,m1,y1 = date1.split("-")
        d2,m2,y2 = date2.split("-")
        d1,m1,y1 = int(d1),int(m1),int(y1)
        d2,m2,y2 = int(d2),int(m2),int(y2)
    except ValueError:
        return -1
    num1 = day_in_year(y1) - day_of_year(d1, m1, y1) + 2
    num2 = day_of_year(d2, m2, y2)
    if (m1 or m2) > 12:
        return(-1)
    if (d1 or d2) == 31 and (m1 or m2) == (4 or 6 and 9 and 11):
        return(-1)

    if day_in_year(y1 or y2):
        if d1 == 29 and m1 == 2:
            return(-1)

    if y2 - y1 > 1:
        count = 0
        count_for = y2 - y1
        for i in range(count_for):
            if i == 0:
                continue
            count += day_in_year(y1 + i)
        return(num1 + num2  + count)-1

    if y1 == y2:
        return num1
    else:
        return(num1 + num2)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 367 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
367
367
365
-1
-1
-1
-1

1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()

In [ ]:
def simulate_fish_population(n, p, month = 40):
    DEADTIME = 5 * 12
    fish_count_history = []
    month_count = 0
    egg_fish = 0
    baby_fish = 0
    adult_fish = 0

    n = n

    for month in range(1, month + 1):
        if month_count >= DEADTIME and fish_count_history:
            n -= fish_count_history.pop(0)
        egg_fish = (n / 2) * 300
        fish_count_history.append(n)
        baby_fish += egg_fish * (1 - p / 100)
        egg_fish -= (n / 2) * 300
        adult_fish = baby_fish * (1 - p / 100)
        display_month = month * 3
        if display_month % 3 == 0:
            print(f'เดือนที่ {display_month} : ไข่ปลา : {int(egg_fish + (n / 2) * 300)} ใบ  ลูกปลา : {int(baby_fish)} ตัว  ปลาเต็มวัย : {int(adult_fish)} ตัว  รวมทั้งหมด : {int(baby_fish + adult_fish + n)} ตัว')

        adult_fish += n
        n = adult_fish

        fish_count_history.append(n)

        month_count += 1

    return egg_fish, baby_fish, adult_fish

month = 40
n = 2
p = 10

egg_fish, baby_fish, adult_fish = simulate_fish_population(n, p, month)

เดือนที่ 3 : ไข่ปลา : 300 ใบ  ลูกปลา : 270 ตัว  ปลาเต็มวัย : 243 ตัว  รวมทั้งหมด : 515 ตัว
เดือนที่ 6 : ไข่ปลา : 36750 ใบ  ลูกปลา : 33345 ตัว  ปลาเต็มวัย : 30010 ตัว  รวมทั้งหมด : 63600 ตัว
เดือนที่ 9 : ไข่ปลา : 4538325 ใบ  ลูกปลา : 4117837 ตัว  ปลาเต็มวัย : 3706053 ตัว  รวมทั้งหมด : 7854146 ตัว
เดือนที่ 12 : ไข่ปลา : 560446387 ใบ  ลูกปลา : 508519586 ตัว  ปลาเต็มวัย : 457667627 ตัว  รวมทั้งหมด : 969923523 ตัว
เดือนที่ 15 : ไข่ปลา : 69210590531 ใบ  ลูกปลา : 62798051064 ตัว  ปลาเต็มวัย : 56518245957 ตัว  รวมทั้งหมด : 119777700959 ตัว
เดือนที่ 18 : ไข่ปลา : 8546947484221 ใบ  ลูกปลา : 7755050786864 ตัว  ปลาเต็มวัย : 6979545708177 ตัว  รวมทั้งหมด : 14791576144936 ตัว
เดือนที่ 21 : ไข่ปลา : 1055478803710870 ใบ  ลูกปลา : 957685974126647 ตัว  ปลาเต็มวัย : 861917376713982 ตัว  รวมทั้งหมด : 1826639876198702 ตัว
เดือนที่ 24 : ไข่ปลา : 130343085310808256 ใบ  ลูกปลา : 118266462753854080 ตัว  ปลาเต็มวัย : 106439816478468672 ตัว  รวมทั้งหมด : 225575233134394816 ตัว
เดือนที่ 27 : ไข่ปลา : 16096315557081108480 ใบ  ลูกปลา : 14604950464126851072 ตัว  ปลาเต็มวัย : 13144455417714165760 ตัว  รวมทั้งหมด : 27856714652221558784 ตัว
เดือนที่ 30 : ไข่ปลา : 1987764628214205906944 ใบ  ลูกปลา : 1803593115856912252928 ตัว  ปลาเต็มวัย : 1623233804271220948992 ตัว  รวมทั้งหมด : 3440078684316227862528 ตัว
เดือนที่ 33 : ไข่ปลา : 245472835268897350352896 ใบ  ลูกปลา : 222729144857864551006208 ตัว  ปลาเต็มวัย : 200456230372078092550144 ตัว  รวมทั้งหมด : 424821860798401947369472 ตัว
เดือนที่ 36 : ไข่ปลา : 30313907391080608850509824 ใบ  ลูกปลา : 27505245796830416079945728 ตัว  ปลาเต็มวัย : 24754721217147373612957696 ตัว  รวมทั้งหมด : 52462059729918327257038848 ตัว
เดือนที่ 39 : ไข่ปลา : 3743522089963186676563968000 ใบ  ลูกปลา : 3396675126763698845894311936 ตัว  ปลาเต็มวัย : 3057007614087328796378136576 ตัว  รวมทั้งหมด : 6478639554784115828327448576 ตัว
เดือนที่ 42 : ไข่ปลา : 462294664203062451707458879488 ใบ  ลูกปลา : 419461872909519865030530564096 ตัว  ปลาเต็มวัย : 377515685618567906674975178752 ตัว  รวมทั้งหมด : 800059522956108062793857499136 ตัว
เดือนที่ 45 : ไข่ปลา : 57089647506988247678897549737984 ใบ  ลูกปลา : 51800144629198944436740687921152 ตัว  ปลาเต็มวัย : 46620130166279050893786544603136 ตัว  รวมทั้งหมด : 98800872445524592535489814200320 ตัว
เดือนที่ 48 : ไข่ปลา : 7050109172448845395358119484194816 ใบ  ลูกปลา : 6396898399833160879321518941667328 ตัว  ปลาเต็มวัย : 5757208559849844560805066126131200 ตัว  รวมทั้งหมด : 12201107687499332106038849979809792 ตัว
เดือนที่ 51 : ไข่ปลา : 870631393149925508763530955480629248 ใบ  ลูกปลา : 789965152234766133523894637841874944 ตัว  ปลาเต็มวัย : 710968637011289490656714656122404864 ตัว  รวมทั้งหมด : 1506737998533722049050057638508756992 ตัว
เดือนที่ 54 : ไข่ปลา : 107515926944843347779105156066753642496 ใบ  ลูกปลา : 97554299402593779606955183384884674560 ตัว  ปลาเต็มวัย : 87798869462334411090992630785686634496 ตัว  รวมทั้งหมด : 186069941711227115622943933339191476224 ตัว
เดือนที่ 57 : ไข่ปลา : 13277346346295007240384979688392289681408 ใบ  ลูกปลา : 12047166011068100073057738911490691301376 ตัว  ปลาเต็มวัย : 10842449409961290791107456789119126994944 ตัว  รวมทั้งหมด : 22978131063338024181291718519085544243200 ตัว
เดือนที่ 60 : ไข่ปลา : 1639644757840488650085019890348844833046528 ใบ  ลูกปลา : 1487727448067507670927920404513161283108864 ตัว  ปลาเต็มวัย : 1338954703260756872886627381927338282319872 ตัว  รวมทั้งหมด : 2837613116380533977098899002508649487663104 ตัว
เดือนที่ 63 : ไข่ปลา : 202482850246954015869259009323308762483654656 ใบ  ลูกปลา : 183722292670326119663071956117537538955018240 ตัว  ปลาเต็มวัย : 165350063403293507696764760505783785059516416 ตัว  รวมทั้งหมด : 350422241741932649642702567543830918796935168 ตัว
เดือนที่ 66 : ไข่ปลา : 25004992360740981953017629656138472376149999616 ใบ  ลูกปลา : 22688215417337210479512973755051128388424040448 ตัว  ปลาเต็มวัย : 20419393875603490445682156562129536746944200704 ตัว  รวมทั้งหมด : 43274309242012309871633717613669255118300643328 ตัว
เดือนที่ 69 : ไข่ปลา : 3087914073701264239498594658287595019222197993472 ใบ  ลูกปลา : 2801810881748475217697018920722172151989926887424 ตัว  ปลาเต็มวัย : 2521629793573627663475461662807282258475332141056 ตัว  รวมทั้งหมด : 5344026769146778599178094238764020467586299854848 ตัว
เดือนที่ 72 : ไข่ปลา : 381332383109745444265561887971492251407187953319936 ใบ  ลูกปลา : 346000955680519366164894347854172884559984121085952 ตัว  ปลาเต็มวัย : 311400860112467446163754860380204007401573962481664 ตัว  รวมทั้งหมด : 659944031680385197813324359134380616415627662327808 ตัว
เดือนที่ 75 : ไข่ปลา : 47091461399979861288831044369757946627300045847789568 ใบ  ลูกปลา : 42728316215662395007957982752668328776760084735721472 ตัว  ปลาเต็มวัย : 38455484594096154443779787849468797576038428037873664 ตัว  รวมทั้งหมด : 81497743885758413704927955618829735011383272231927808 ตัว
เดือนที่ 78 : ไข่ปลา : 5815414150514403059757271120628058532724433698257108992 ใบ  ลูกปลา : 5276601051678624972268024151081093086603172807937359872 ตัว  ปลาเต็มวัย : 4748940946510762883380062041099139933992384445265477632 ตัว  รวมทั้งหมด : 10064311425859483236315618188286775433002791506133647360 ตัว
เดือนที่ 81 : ไข่ปลา : 718156556127128878442344809323745445016782636890873397248 ใบ  ลูกปลา : 651617501566094677093430291848126187779836569673416048640 ตัว  ปลาเต็มวัย : 586455751409485252940230228543436892313802663972405510144 ตัว  รวมทั้งหมด : 1242860963349760909438230738282861755401399098053501124608 ตัว
เดือนที่ 84 : ไข่ปลา : 88686519267549917603487452476681499111702277755545659113472 ใบ  ลูกปลา : 80469484842361030294230619064361149139513410733829200543744 ตัว  ปลาเต็มวัย : 72422536358124925034733037304862720071990242395610129891328 ตัว  รวมทั้งหมด : 153483264662269615202111583797160599575580551972935079821312 ตัว
เดือนที่ 87 : ไข่ปลา : 10952066972986290010858154960043478002053334995998755501637632 ใบ  ลูกปลา : 9937329760530021999925228725748369696223222016365658441252864 ตัว  ปลาเต็มวัย : 8943596784477019942657475123769520832429496759678606235402240 ตัว  รวมทั้งหมด : 18953940324826948944137675718576446930052788559249703631323136 ตัว
เดือนที่ 90 : ไข่ปลา : 1352491584644539232883057871522835646884754887664955053798588416 ใบ  ลูกปลา : 1227179755940615416373190259830317386754689206214836307995131904 ตัว  ปลาเต็มวัย : 1104461780346553819929559833938426215441039058732739440098148352 ตัว  รวมทั้งหมด : 2340658146851466404451822608068791578279886668455137841967529984 ตัว
เดือนที่ 93 : ไข่ปลา : 167021758636627617154885058954084116900476924115031062407293173760 ใบ  ลูกปลา : 151546762528905480538218090635737855696595937655117797695112085504 ตัว  ปลาเต็มวัย : 136392086276014941838006760489942746630519273273817343723569152000 ตัว  รวมทั้งหมด : 289052327195831291085010836111116959738319005076107056280835719168 ตัว
เดือนที่ 96 : ไข่ปลา : 20625834700038868682399663356795475890147752004042877790488379785216 ใบ  ลูกปลา : 18714797992563887565952619000367247775433477693435836257275733868544 ตัว  ปลาเต็มวัย : 16843318193307498210726286449592687701660822443502727780478190878720 ตัว  รวมทั้งหมด : 35695621750538307237796825498668230006969961040701286800284400484352 ตัว
เดือนที่ 99 : ไข่ปลา : 2547123563696163489544594560409199101336849234620389947414272635043840 ใบ  ลูกปลา : 2311126005319111111964437614471943380450700836134320268079916849823744 ตัว  ปลาเต็มวัย : 2080013404787200039080382374671970501364306431278617831740403219431424 ตัว  รวมทั้งหมด : 4408120233864285804182781749429970629575973668190118242280616881029120 ตัว
เดือนที่ 102 : ไข่ปลา : 314549134281776147896664378638760757289124433822084494046127044979326976 ใบ  ลูกปลา : 285405346858917625599141556868806995886746311399753783941913922800451584 ตัว  ปลาเต็มวัย : 256864812173025848327270208869393256057940219616810242807826957557825536 ตัว  รวมทั้งหมด : 544367153260488626014320882101297618408193153381559366347539528181350400 ตัว
เดือนที่ 105 : ไข่ปลา : 38844270960235650748834901092791801922756494460609351622038967545388597248 ใบ  ลูกปลา : 35245249211071002975887494309505701841084699191802870663499282108473409536 ตัว  ปลาเต็มวัย : 31720724289963906444559786110563589958449883197222433258562620576046776320 ตัว  รวมทั้งหมด : 67224935307436486158525764747189668115707298881764692973026801745307631616 ตัว
เดือนที่ 108 : ไข่ปลา : 4796952914454821573493090669970564948839713011590309427689943942704163454976 ใบ  ลูกปลา : 4352502872220410466825642286221787960948826026001346117962350208468882817024 ตัว  ปลาเต็มวัย : 3917252584998369661183784696448150496148257274575601884496564255040919830528 ตัว  รวมทั้งหมด : 8301735143315146264010645733322421862293805913864217099413408207406226210816 ตัว
เดือนที่ 111 : ไข่ปลา : 592384840664210284410034171338610481477756089097812713540900029352581238095872 ใบ  ลูกปลา : 537498859470009665953774983213274138628340678511684007548111478490954146512896 ตัว  ปลาเต็มวัย : 483748973523008689073994001634408961296949219677074950651201170431984585932800 ตัว  รวมทั้งหมด : 1025197065264112885940353345273523602226468104578390007599881999615789574914048 ตัว
เดือนที่ 114 : ไข่ปลา : 73154730869115517759270527719515060063443095434035317768060739678099927499538432 ใบ  ลูกปลา : 66376756641673985913131926221799516137347402770617244828617739078235286533046272 ตัว  ปลาเต็มวัย : 59739080977506595220240608741408566867464738768837944262888120211595101953064960 ตัว  รวมทั้งหมด : 126603535824974706876202741659276034464550955219256932042754790670579603498598400 ตัว
เดือนที่ 117 : ไข่ปลา : 9034016877495103931968955573334009832359425520478660326316741716887197372393717760 ใบ  ลูกปลา : 8196991946387268051246650285008341854850968789553573132989162287022269193242279936 ตัว  ปลาเต็มวัย : 7377292751748541414621651926199006386034716204470907529922398699198620280815616000 ตัว  รวมทั้งหมด : 15634511477319109765582206352416077967540777811791391074545316435616788773779537920 ตัว
เดือนที่ 120 : ไข่ปลา : 1115627929639776290850266744049460160237240212110211033279853650464893538460101509120 ใบ  ลูกปลา : 1012262128622186115166120056590171074404095882948704384340225352671862261394654101504 ตัว  ปลาเต็มวัย : 911035915759967568353380052092689474164522503500947562635349431502049989903853289472 ตัว  รวมทั้งหมด : 1930735563913085575783735665657717899681961483633697277986776730586080172948313866240 ตัว

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน

In [ ]:
def find_mismatch(str1, str2):
    i,j = 0,0
    count = 1
    str1, str2 = str1.lower(), str2.lower()

    if str1 == str2:
        return 0
    elif abs(len(str1) - len(str2)) >= 2:
        return 2

    while (i < len(str1)) and (j < len(str2)):

        if str1[i] != str2[j]:

            if count == 0:
                return 2
            else:
                count -= 1

            if len(str1) > len(str2):
                i += 1
            elif len(str1) < len(str2):
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1
    return 1

print(find_mismatch("Python", "Java"))
print(find_mismatch("book", "boot"))
print(find_mismatch("fan", "fun"))
print(find_mismatch("sin", "sink"))
print(find_mismatch("Dog", "dog"))
print(find_mismatch("poke", "spoke"))
print(find_mismatch("poker", "poke"))

2
1
1
1
0
1
1

3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|

In [ ]:
def find_mismatch(str1, str2):
    i,j = 0,0
    count = 1
    str1, str2 = str1.lower(), str2.lower()

    if str1 == str2:
        return 0
    elif abs(len(str1) - len(str2)) >= 2:
        return 2

    while (i < len(str1)) and (j < len(str2)):

        if str1[i] != str2[j]:

            if count == 0:
                return 2
            else:
                count -= 1

            if len(str1) > len(str2):
                i += 1
            elif len(str1) < len(str2):
                j += 1
            else:
                i += 1
                j += 1
        else:
            i += 1
            j += 1
    return 1

def spelling_correction(input_string, correct_spells):
    output = ""
    words = input_string.split()

    for word in words:
        if len(word) <= 2:
            output += word + " "
        else:
            _min = 3
            most_similar_word = ""
            for e in correct_spells:
                result = find_mismatch(word, e)
                if result < _min:
                    _min = result
                    most_similar_word = e
            if _min == 1:
                output += most_similar_word.lower() + " "
            else:
                output += word.lower() + " "

    return output[:-1]

correct_spells = ["that", "first", "case", "car"]
input_string = "Thes is the Firs cas"
output_string = spelling_correction(input_string, correct_spells)
print(output_string)

# correct_spells = ["we", "live", "ln", "Python"]
# input_string = "Wee lpve Pythen"
# output_string = spelling_correction(input_string, correct_spells)
# print(output_string)

thes is the first case

4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]

In [ ]:
def find_word_horizontal(crosswords, word):
    for index, row in enumerate(crosswords):
        str_row = ''.join(row)
        if word in str_row:
            new_word = str_row.index(word)
            return [index , new_word]
    return None

crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
word = 'cat'
print(find_word_horizontal(crosswords, word))

[2, 1]

5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]

In [ ]:
def find_word_vertical(crosswords,word):
    for index , col in enumerate(zip(*crosswords)):
        str_col = ''.join(col)
        if word in str_col:
            new_word = str_col.index(word)
            return[new_word,index]
    return None
crosswords = [['s','d','o','g'],
             ['c','u','c','m'],
             ['a','c','a','t'],
             ['t',' e','t','k']]
word='cat'
print(find_word_vertical(crosswords,word))

[1, 0]

6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```

In [ ]:
def find_word_vertical(crosswords,word):
    for index , col in enumerate(zip(*crosswords)):
        str_col = ''.join(col)
        if word in str_col:
            new_word = str_col.index(word)
            return[new_word,index]
    return None

def find_word_horizontal(crosswords, word):

    for index, row in enumerate(crosswords):
        str_row = ''.join(row)
        if word in str_row:
            new_word = str_row.index(word)
            return [index , new_word]
    return None

def capitalize_word_in_crossword(crosswords,word):
    vertical = find_word_vertical(crosswords,word)
    horizontal = find_word_horizontal(crosswords,word)
    if (vertical is None) and (horizontal is None) :
        return crosswords
    if (vertical is not None) and (horizontal is not None):
        vertical = None

    modi_output = [row[:] for row in crosswords]

    if (vertical is not None) :
        row_idx , col_idx = vertical
        for i in range(len(word)):
            modi_output[row_idx+i][col_idx] = modi_output[row_idx+i][col_idx].upper()
    if (horizontal is not None):
        row_idx,col_idx= horizontal
        for i in range(len(word)):
            modi_output[row_idx][col_idx+i] = modi_output[row_idx][col_idx+i].upper()

    return modi_output

crosswords=[['s','d','o','g'],['c','u','c','m'],['a','c','a','t'],['t','e','t','k']]
word='cat'

for row in capitalize_word_in_crossword(crosswords,word):
  print(row)

['s', 'd', 'o', 'g']
['c', 'u', 'c', 'm']
['a', 'C', 'A', 'T']
['t', 'e', 't', 'k']